// Generates the native design system from the shared sources, so iOS and Android never hand-type a
// colour, size or icon:
//   tokens.json → apps/ios/Padel/Design/Tokens.swift, apps/android/.../ui/theme/Tokens.kt
//   icons.ts    → apps/ios/Shared/Icons.xcassets (template SVGs), Android VectorDrawables
//   fonts/      → apps/ios/Shared/Fonts, Android res/font
// Run: npm run native -w @padel/design (also part of `make native-assets`).
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { ICONS, iconSvg, type IconName } from '../icons.ts';

const root = new URL('../../../', import.meta.url);
const tokens = JSON.parse(readFileSync(new URL('packages/design/tokens.json', root), 'utf8'));
const HEADER = 'Generated by packages/design/scripts/export-native.ts from packages/design. Do not edit.';

const IOS = new URL('apps/ios/Padel/', root);
/** Compiled into the app and the widget extension. */
const IOS_SHARED = new URL('apps/ios/Shared/', root);
const ANDROID_RES = new URL('apps/android/app/src/main/res/', root);
const ANDROID_THEME = new URL('apps/android/app/src/main/java/app/americanoo/android/ui/theme/', root);

function write(url: URL, text: string) {
  mkdirSync(new URL('.', url), { recursive: true });
  writeFileSync(url, text);
}

const camel = (s: string) => s.replace(/[-_](\w)/g, (_, c: string) => c.toUpperCase());
const pascal = (s: string) => camel(s).replace(/^\w/, (c) => c.toUpperCase());
/** Swift/Kotlin identifiers can't start with a digit: "2xl" → "xl2". */
const ident = (s: string) => (/^\d/.test(s) ? s.replace(/^(\d+)(.*)$/, '$2$1') : camel(s));
const hex = (h: string) => h.replace('#', '').toUpperCase();

type Palette = Record<string, string>;
const light: Palette = tokens.color.light;
const dark: Palette = tokens.color.dark;
const state: Palette = tokens.color.state;

/* ------------------------------------------------------------------ */
/* Swift                                                                */
/* ------------------------------------------------------------------ */

function swift(): string {
  const rgb = (h: string) => {
    const n = parseInt(hex(h), 16);
    const c = (v: number) => +(v / 255).toFixed(4);
    return `red: ${c((n >> 16) & 255)}, green: ${c((n >> 8) & 255)}, blue: ${c(n & 255)}`;
  };
  const colors = Object.keys(light)
    .map((k) => `    static let ${camel(k)} = Color(light: UIColor(${rgb(light[k])}, alpha: 1), dark: UIColor(${rgb(dark[k])}, alpha: 1))`)
    .join('\n');
  const states = Object.entries(state)
    .map(([k, v]) => `    static let ${camel(k)} = Color(${rgb(v)})`)
    .join('\n');
  const radius = Object.entries(tokens.radius as Record<string, number>).map(([k, v]) => `        static let ${ident(k)}: CGFloat = ${v}`).join('\n');
  const space = (tokens.space as number[]).map((v, i) => `        static let s${i}: CGFloat = ${v}`).join('\n');
  const sizes = Object.entries(tokens.font.size as Record<string, number>).map(([k, v]) => `        static let ${ident(k)}: CGFloat = ${v}`).join('\n');

  return `// ${HEADER}
import SwiftUI
import UIKit

extension Color {
    /// Resolves per trait collection, so light/dark follow the system (and \`.preferredColorScheme\`).
    init(light: UIColor, dark: UIColor) {
        self.init(uiColor: UIColor { $0.userInterfaceStyle == .dark ? dark : light })
    }
}

/// Black & white, casual-professional. Colour only for functional state (PRD §3a).
enum Palette {
${colors}

    // Functional state only: rank movement and errors, always paired with an icon or text.
${states}
}

enum Tokens {
    enum Radius {
${radius}
    }

    /// Spacing scale: s0…s${tokens.space.length - 1} = ${tokens.space.join(', ')} pt.
    enum Space {
${space}
    }

    enum FontSize {
${sizes}
    }

    static let touchTarget: CGFloat = ${tokens.touchTarget}
    static let iconSize: CGFloat = ${tokens.icon.size}
    static let motionFast: Double = ${tokens.motion.fast / 1000}
    static let motionBase: Double = ${tokens.motion.base / 1000}
}

enum PadelFont {
    static let family = "${tokens.font.family}"
    static let mono = "${tokens.font.mono}"
}

/// Custom icon set (packages/design/icons.ts), template images in Shared/Icons.xcassets.
enum PadelIcon: String, CaseIterable {
${(Object.keys(ICONS) as IconName[]).map((n) => `    case ${camel(n)} = "icon-${n}"`).join('\n')}

    var image: Image { Image(rawValue) }
}
`;
}

/* ------------------------------------------------------------------ */
/* Kotlin                                                               */
/* ------------------------------------------------------------------ */

function kotlin(): string {
  const col = (h: string) => `Color(0xFF${hex(h)})`;
  const scheme = (p: Palette) =>
    Object.keys(p)
      .map((k) => `    val ${camel(k)} = ${col(p[k])}`)
      .join('\n');
  return `// ${HEADER}
package app.americanoo.android.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import app.americanoo.android.R

/** Black & white, casual-professional. Colour only for functional state (PRD §3a). */
object LightPalette {
${scheme(light)}
}

object DarkPalette {
${scheme(dark)}
}

/** Functional state only: rank movement and errors, always paired with an icon or text. */
object StateColors {
${Object.entries(state).map(([k, v]) => `    val ${camel(k)} = ${col(v)}`).join('\n')}
}

object Radius {
${Object.entries(tokens.radius as Record<string, number>).map(([k, v]) => `    val ${ident(k)} = ${v}.dp`).join('\n')}
}

/** Spacing scale: s0…s${tokens.space.length - 1} = ${tokens.space.join(', ')} dp. */
object Space {
${(tokens.space as number[]).map((v, i) => `    val s${i} = ${v}.dp`).join('\n')}
}

object FontSize {
${Object.entries(tokens.font.size as Record<string, number>).map(([k, v]) => `    val ${ident(k)} = ${v}.sp`).join('\n')}
}

object Tokens {
    val touchTarget = ${tokens.touchTarget}.dp
    val iconSize = ${tokens.icon.size}.dp
    const val MOTION_FAST = ${tokens.motion.fast}
    const val MOTION_BASE = ${tokens.motion.base}
}

/** Custom icon set (packages/design/icons.ts) as VectorDrawables. */
enum class PadelIcon(val res: Int) {
${(Object.keys(ICONS) as IconName[]).map((n) => `    ${pascal(n)}(R.drawable.ic_${n.replace(/-/g, '_')}),`).join('\n')}
}
`;
}

/* ------------------------------------------------------------------ */
/* SVG → VectorDrawable                                                 */
/* ------------------------------------------------------------------ */

interface Node {
  tag: string;
  attrs: Record<string, string>;
  children: Node[];
}

function parse(markup: string): Node[] {
  const rootNode: Node = { tag: 'root', attrs: {}, children: [] };
  const stack = [rootNode];
  const re = /<(\/?)(\w+)([^>]*?)(\/?)>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(markup))) {
    const [, closing, tag, rawAttrs, selfClosing] = m;
    if (closing) {
      stack.pop();
      continue;
    }
    const attrs: Record<string, string> = {};
    for (const a of rawAttrs.matchAll(/([\w-]+)="([^"]*)"/g)) attrs[a[1]] = a[2];
    const node: Node = { tag, attrs, children: [] };
    stack[stack.length - 1].children.push(node);
    if (!selfClosing) stack.push(node);
  }
  return rootNode.children;
}

const n = (s: string | undefined, d = 0) => (s === undefined ? d : parseFloat(s));

function toPathData(node: Node): string {
  const a = node.attrs;
  switch (node.tag) {
    case 'path':
      return a.d;
    case 'circle': {
      const [cx, cy, r] = [n(a.cx), n(a.cy), n(a.r)];
      return `M${cx - r},${cy}a${r},${r} 0 1,0 ${2 * r},0a${r},${r} 0 1,0 ${-2 * r},0Z`;
    }
    case 'rect': {
      const [x, y, w, h] = [n(a.x), n(a.y), n(a.width), n(a.height)];
      const r = Math.min(n(a.rx), w / 2, h / 2);
      if (!r) return `M${x},${y}h${w}v${h}h${-w}Z`;
      return (
        `M${x + r},${y}h${w - 2 * r}a${r},${r} 0 0,1 ${r},${r}v${h - 2 * r}a${r},${r} 0 0,1 ${-r},${r}` +
        `h${-(w - 2 * r)}a${r},${r} 0 0,1 ${-r},${-r}v${-(h - 2 * r)}a${r},${r} 0 0,1 ${r},${-r}Z`
      );
    }
    default:
      throw new Error(`Unsupported SVG element <${node.tag}>`);
  }
}

interface Style {
  fill: string;
  stroke: string;
  strokeWidth: number;
  opacity: number;
  fillOpacity: number;
  fillRule: string;
}

function vector(name: IconName): string {
  const out: string[] = [];
  const base: Style = { fill: 'none', stroke: 'currentColor', strokeWidth: tokens.icon.stroke, opacity: 1, fillOpacity: 1, fillRule: 'nonzero' };

  const walk = (nodes: Node[], inherited: Style, indent: string) => {
    for (const node of nodes) {
      const a = node.attrs;
      const s: Style = {
        fill: a.fill ?? inherited.fill,
        stroke: a.stroke ?? inherited.stroke,
        strokeWidth: n(a['stroke-width'], inherited.strokeWidth),
        opacity: inherited.opacity * n(a.opacity, 1),
        fillOpacity: n(a['fill-opacity'], inherited.fillOpacity),
        fillRule: a['fill-rule'] ?? inherited.fillRule,
      };
      if (node.tag === 'g') {
        const rot = a.transform?.match(/rotate\(([-\d.]+)\s+([-\d.]+)\s+([-\d.]+)\)/);
        out.push(`${indent}<group${rot ? ` android:rotation="${rot[1]}" android:pivotX="${rot[2]}" android:pivotY="${rot[3]}"` : ''}>`);
        walk(node.children, s, indent + '    ');
        out.push(`${indent}</group>`);
        continue;
      }
      const attrs = [`android:pathData="${toPathData(node)}"`];
      if (s.fill !== 'none') {
        attrs.push('android:fillColor="@android:color/white"');
        if (s.fillOpacity * s.opacity !== 1) attrs.push(`android:fillAlpha="${+(s.fillOpacity * s.opacity).toFixed(3)}"`);
        if (s.fillRule === 'evenodd') attrs.push('android:fillType="evenOdd"');
      }
      if (s.stroke !== 'none') {
        attrs.push(
          'android:strokeColor="@android:color/white"',
          `android:strokeWidth="${s.strokeWidth}"`,
          'android:strokeLineCap="round"',
          'android:strokeLineJoin="round"',
        );
        if (s.opacity !== 1) attrs.push(`android:strokeAlpha="${s.opacity}"`);
      }
      out.push(`${indent}<path\n${indent}    ${attrs.join(`\n${indent}    `)} />`);
    }
  };
  walk(parse(ICONS[name]), base, '    ');

  // White paths: Compose's Icon() tints them with LocalContentColor; the launcher shows them as-is.
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- ${HEADER} -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
${out.join('\n')}
</vector>
`;
}

/* ------------------------------------------------------------------ */

function iosAssets() {
  const catalog = new URL('Icons.xcassets/', IOS_SHARED);
  rmSync(catalog, { recursive: true, force: true });
  write(new URL('Contents.json', catalog), JSON.stringify({ info: { author: 'xcode', version: 1 } }, null, 2) + '\n');
  for (const name of Object.keys(ICONS) as IconName[]) {
    const set = new URL(`icon-${name}.imageset/`, catalog);
    write(new URL(`${name}.svg`, set), iconSvg(name, 24, tokens.icon.stroke).replace(/currentColor/g, '#000000') + '\n');
    write(
      new URL('Contents.json', set),
      JSON.stringify(
        {
          images: [{ filename: `${name}.svg`, idiom: 'universal' }],
          info: { author: 'xcode', version: 1 },
          properties: { 'preserves-vector-representation': true, 'template-rendering-intent': 'template' },
        },
        null,
        2,
      ) + '\n',
    );
  }
}

function fonts() {
  const src = new URL('packages/design/fonts/', root);
  for (const [file, res] of [
    ['Geist.ttf', 'geist.ttf'],
    ['GeistMono.ttf', 'geist_mono.ttf'],
  ]) {
    mkdirSync(new URL('Fonts/', IOS_SHARED), { recursive: true });
    copyFileSync(new URL(file, src), new URL(`Fonts/${file}`, IOS_SHARED));
    mkdirSync(new URL('font/', ANDROID_RES), { recursive: true });
    copyFileSync(new URL(file, src), new URL(`font/${res}`, ANDROID_RES));
  }
}

write(new URL('Design/Tokens.swift', IOS), swift());
write(new URL('Tokens.kt', ANDROID_THEME), kotlin());
iosAssets();
for (const name of Object.keys(ICONS) as IconName[]) write(new URL(`drawable/ic_${name.replace(/-/g, '_')}.xml`, ANDROID_RES), vector(name));
fonts();
console.log(`Native design system: tokens, ${Object.keys(ICONS).length} icons and fonts → apps/ios, apps/android`);
