package app.americanoo.engine

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.double
import kotlinx.serialization.json.int
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.fail

internal expect fun readFixture(name: String): String

/**
 * Replays the JSON files in packages/engine/fixtures (generated by the TS engine) against the Kotlin port.
 * Any divergence is an engine drift bug: the TS engine is the source of truth.
 */
class FixturesTest {
    private val json = Json { ignoreUnknownKeys = true }

    private inline fun <reified T> load(name: String): List<T> = json.decodeFromString(readFixture(name))

    @Serializable
    data class RngCase(val seed: String, val values: List<Double>, val shuffle: List<String>)

    @Test
    fun rng() {
        for (c in load<RngCase>("rng.json")) {
            val rng = createRng(c.seed)
            assertEquals(c.values, List(c.values.size) { rng.next() }, "rng values for seed '${c.seed}'")
            val names = "Anna Mikko Laura Jussi Sara Pekka Emma Olli Aino Ville Iida Timo".split(" ")
            assertEquals(c.shuffle, shuffle(names, createRng("${c.seed}:shuffle")), "shuffle for seed '${c.seed}'")
        }
    }

    @Test
    fun normalizeScore() {
        for (c in load<JsonObject>("score.json")) {
            val scoring = json.decodeFromJsonElement(Scoring.serializer(), c.getValue("scoring"))
            val a = c.getValue("a").jsonPrimitive.double
            val b = c["b"]?.jsonPrimitive?.takeIf { it.content != "null" }?.double
            val result = c.getValue("result").jsonObject
            val label = "normalizeScore($scoring, $a, $b)"
            // Fractional input can't be expressed with Int; the TS engine must reject it.
            if (a % 1.0 != 0.0 || (b != null && b % 1.0 != 0.0)) {
                assertEquals("INVALID_SCORE", result["error"]?.jsonPrimitive?.content, label)
                continue
            }
            val actual = runCatching { normalizeScore(scoring, a.toInt(), b?.toInt()) }
            when (val error = result["error"]) {
                null -> {
                    val ok = result.getValue("ok").jsonArray.map { it.jsonPrimitive.int }
                    assertEquals(Pair(ok[0], ok[1]), actual.getOrElse { fail("$label threw $it") }, label)
                }
                else -> assertEquals(error.jsonPrimitive.content, (actual.exceptionOrNull() as? EngineError)?.code, label)
            }
        }
    }

    @Serializable
    data class ValidateCase(val settings: Settings, val players: List<Player>, val errors: List<ValidationError>)

    @Test
    fun validate() {
        for (c in load<ValidateCase>("validate.json")) {
            assertEquals(c.errors, validate(c.settings, c.players), "validate ${c.settings} with ${c.players.size} players")
        }
    }

    @Serializable
    data class EstimateCase(val settings: Settings, val players: Int, val autoRounds: Int, val estimate: Estimate, val duration: String)

    @Test
    fun estimate() {
        for (c in load<EstimateCase>("estimate.json")) {
            val label = "estimate ${c.settings} / ${c.players} players"
            assertEquals(c.autoRounds, autoRounds(c.settings, c.players), label)
            assertEquals(c.estimate, estimate(c.settings, c.players), label)
            assertEquals(c.duration, formatDuration(c.estimate.minutes), label)
        }
    }

    @Serializable
    data class DefaultsCase(val mode: ModeInfo, val defaults: List<Default>) {
        @Serializable
        data class Default(val players: Int, val settings: Settings)
    }

    @Test
    fun modesAndDefaults() {
        val cases = load<DefaultsCase>("defaults.json")
        assertEquals(cases.map { it.mode }, MODES)
        for (c in cases) for (d in c.defaults) {
            assertEquals(d.settings, defaultSettings(c.mode.id, d.players), "defaults for ${c.mode.id} / ${d.players}")
        }
    }

    @Serializable
    data class GameCase(
        val name: String,
        val settings: Settings,
        val players: List<Player>,
        val seed: String,
        val steps: List<JsonObject>,
        val expect: Expect,
    ) {
        @Serializable
        data class Expect(
            val initial: GameState,
            val final: GameState,
            val status: AdvanceStatus,
            val standings: List<Standing>,
            val standingsByRound: List<List<Standing>>,
        )
    }

    @Test
    fun games() {
        val cases = load<GameCase>("games.json")
        check(cases.size >= 30) { "expected the full scenario set, got ${cases.size}" }
        for (c in cases) {
            var g = createGame(c.settings, c.players, c.seed)
            assertRounds(c.expect.initial, g, "${c.name}: createGame")
            c.steps.forEachIndexed { i, step ->
                val label = "${c.name} step $i $step"
                when (step.str("op")) {
                    "score" -> {
                        val res = setScore(g, step.int("round"), step.int("match"), step.intOrNull("a"), step.intOrNull("b"))
                        assertEquals(step.getValue("regenerated").jsonArray.map { it.jsonPrimitive.int }, res.regenerated, label)
                        g = res.state
                    }
                    "next" -> {
                        assertEquals(step.str("status"), json.encodeToJsonElement(AdvanceStatus.serializer(), advanceStatus(g)).jsonPrimitive.content, label)
                        g = nextRound(g)
                    }
                    "swap" -> g = swapPlayers(g, step.int("round"), step.str("a"), step.str("b"))
                    else -> fail("unknown op in $label")
                }
            }
            assertRounds(c.expect.final, g, "${c.name}: final")
            assertEquals(c.expect.final, g, "${c.name}: final state")
            assertEquals(c.expect.status, advanceStatus(g), "${c.name}: status")
            assertEquals(c.expect.standings, computeStandings(g), "${c.name}: standings")
            c.expect.standingsByRound.forEachIndexed { i, table ->
                assertEquals(table, computeStandings(g, i + 1), "${c.name}: standings up to round ${i + 1}")
            }
        }
    }

    /** Round-by-round comparison first, so a drift names the first diverging round. */
    private fun assertRounds(expected: GameState, actual: GameState, label: String) {
        expected.rounds.forEachIndexed { i, r ->
            assertEquals(r, actual.rounds.getOrNull(i), "$label: round $i")
        }
        assertEquals(expected, actual, label)
    }

    private fun JsonObject.str(k: String) = getValue(k).jsonPrimitive.content
    private fun JsonObject.int(k: String) = getValue(k).jsonPrimitive.int
    private fun JsonObject.intOrNull(k: String): Int? = get(k)?.jsonPrimitive?.takeIf { it.content != "null" }?.int
}
