// Generated by packages/design/scripts/export-native.ts from packages/design. Do not edit.
import SwiftUI
import UIKit

extension Color {
    /// Resolves per trait collection, so light/dark follow the system (and `.preferredColorScheme`).
    init(light: UIColor, dark: UIColor) {
        self.init(uiColor: UIColor { $0.userInterfaceStyle == .dark ? dark : light })
    }
}

/// Black & white, casual-professional. Colour only for functional state (PRD §3a).
enum Palette {
    static let background = Color(light: UIColor(red: 1, green: 1, blue: 1, alpha: 1), dark: UIColor(red: 0.0392, green: 0.0392, blue: 0.0392, alpha: 1))
    static let foreground = Color(light: UIColor(red: 0.0392, green: 0.0392, blue: 0.0392, alpha: 1), dark: UIColor(red: 0.9804, green: 0.9804, blue: 0.9804, alpha: 1))
    static let surface = Color(light: UIColor(red: 0.9804, green: 0.9804, blue: 0.9804, alpha: 1), dark: UIColor(red: 0.0784, green: 0.0784, blue: 0.0784, alpha: 1))
    static let muted = Color(light: UIColor(red: 0.9608, green: 0.9608, blue: 0.9608, alpha: 1), dark: UIColor(red: 0.1216, green: 0.1216, blue: 0.1216, alpha: 1))
    static let mutedForeground = Color(light: UIColor(red: 0.451, green: 0.451, blue: 0.451, alpha: 1), dark: UIColor(red: 0.6392, green: 0.6392, blue: 0.6392, alpha: 1))
    static let border = Color(light: UIColor(red: 0.898, green: 0.898, blue: 0.898, alpha: 1), dark: UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1))
    static let primary = Color(light: UIColor(red: 0.0392, green: 0.0392, blue: 0.0392, alpha: 1), dark: UIColor(red: 0.9804, green: 0.9804, blue: 0.9804, alpha: 1))
    static let primaryForeground = Color(light: UIColor(red: 1, green: 1, blue: 1, alpha: 1), dark: UIColor(red: 0.0392, green: 0.0392, blue: 0.0392, alpha: 1))

    // Functional state only: rank movement and errors, always paired with an icon or text.
    static let up = Color(red: 0.0824, green: 0.502, blue: 0.2392)
    static let down = Color(red: 0.7255, green: 0.1098, blue: 0.1098)
    static let error = Color(red: 0.8627, green: 0.149, blue: 0.149)
}

enum Tokens {
    enum Radius {
        static let sm: CGFloat = 6
        static let md: CGFloat = 10
        static let lg: CGFloat = 14
        static let xl: CGFloat = 20
        static let full: CGFloat = 9999
    }

    /// Spacing scale: s0…s10 = 0, 4, 8, 12, 16, 20, 24, 32, 40, 48, 64 pt.
    enum Space {
        static let s0: CGFloat = 0
        static let s1: CGFloat = 4
        static let s2: CGFloat = 8
        static let s3: CGFloat = 12
        static let s4: CGFloat = 16
        static let s5: CGFloat = 20
        static let s6: CGFloat = 24
        static let s7: CGFloat = 32
        static let s8: CGFloat = 40
        static let s9: CGFloat = 48
        static let s10: CGFloat = 64
    }

    enum FontSize {
        static let xs: CGFloat = 12
        static let sm: CGFloat = 14
        static let base: CGFloat = 16
        static let lg: CGFloat = 18
        static let xl: CGFloat = 20
        static let xl2: CGFloat = 24
        static let xl3: CGFloat = 30
        static let xl4: CGFloat = 36
        static let xl5: CGFloat = 48
        static let score: CGFloat = 56
    }

    static let touchTarget: CGFloat = 44
    static let iconSize: CGFloat = 24
    static let motionFast: Double = 0.15
    static let motionBase: Double = 0.2
}

enum PadelFont {
    static let family = "Geist"
    static let mono = "Geist Mono"
}

/// Custom icon set (packages/design/icons.ts), template images in Shared/Icons.xcassets.
enum PadelIcon: String, CaseIterable {
    case logo = "icon-logo"
    case racket = "icon-racket"
    case ball = "icon-ball"
    case court = "icon-court"
    case rotate = "icon-rotate"
    case pair = "icon-pair"
    case ladder = "icon-ladder"
    case mixed = "icon-mixed"
    case box = "icon-box"
    case updown = "icon-updown"
    case podium = "icon-podium"
    case scoreboard = "icon-scoreboard"
    case leaderboard = "icon-leaderboard"
    case sitout = "icon-sitout"
    case timer = "icon-timer"
    case share = "icon-share"
    case group = "icon-group"
    case agent = "icon-agent"

    var image: Image { Image(rawValue) }
}
