// Generated by packages/design/scripts/export-native.ts from packages/design. Do not edit.
package app.padel.android.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import app.padel.android.R

/** Black & white, casual-professional. Colour only for functional state (PRD §3a). */
object LightPalette {
    val background = Color(0xFFFFFFFF)
    val foreground = Color(0xFF0A0A0A)
    val surface = Color(0xFFFAFAFA)
    val muted = Color(0xFFF5F5F5)
    val mutedForeground = Color(0xFF737373)
    val border = Color(0xFFE5E5E5)
    val primary = Color(0xFF0A0A0A)
    val primaryForeground = Color(0xFFFFFFFF)
}

object DarkPalette {
    val background = Color(0xFF0A0A0A)
    val foreground = Color(0xFFFAFAFA)
    val surface = Color(0xFF141414)
    val muted = Color(0xFF1F1F1F)
    val mutedForeground = Color(0xFFA3A3A3)
    val border = Color(0xFF262626)
    val primary = Color(0xFFFAFAFA)
    val primaryForeground = Color(0xFF0A0A0A)
}

/** Functional state only: rank movement and errors, always paired with an icon or text. */
object StateColors {
    val up = Color(0xFF15803D)
    val down = Color(0xFFB91C1C)
    val error = Color(0xFFDC2626)
}

object Radius {
    val sm = 6.dp
    val md = 10.dp
    val lg = 14.dp
    val xl = 20.dp
    val full = 9999.dp
}

/** Spacing scale: s0…s10 = 0, 4, 8, 12, 16, 20, 24, 32, 40, 48, 64 dp. */
object Space {
    val s0 = 0.dp
    val s1 = 4.dp
    val s2 = 8.dp
    val s3 = 12.dp
    val s4 = 16.dp
    val s5 = 20.dp
    val s6 = 24.dp
    val s7 = 32.dp
    val s8 = 40.dp
    val s9 = 48.dp
    val s10 = 64.dp
}

object FontSize {
    val xs = 12.sp
    val sm = 14.sp
    val base = 16.sp
    val lg = 18.sp
    val xl = 20.sp
    val xl2 = 24.sp
    val xl3 = 30.sp
    val xl4 = 36.sp
    val xl5 = 48.sp
    val score = 56.sp
}

object Tokens {
    val touchTarget = 44.dp
    val iconSize = 24.dp
    const val MOTION_FAST = 150
    const val MOTION_BASE = 200
}

/** Custom icon set (packages/design/icons.ts) as VectorDrawables. */
enum class PadelIcon(val res: Int) {
    Logo(R.drawable.ic_logo),
    Racket(R.drawable.ic_racket),
    Ball(R.drawable.ic_ball),
    Court(R.drawable.ic_court),
    Rotate(R.drawable.ic_rotate),
    Pair(R.drawable.ic_pair),
    Ladder(R.drawable.ic_ladder),
    Mixed(R.drawable.ic_mixed),
    Box(R.drawable.ic_box),
    Updown(R.drawable.ic_updown),
    Podium(R.drawable.ic_podium),
    Scoreboard(R.drawable.ic_scoreboard),
    Leaderboard(R.drawable.ic_leaderboard),
    Sitout(R.drawable.ic_sitout),
    Timer(R.drawable.ic_timer),
    Share(R.drawable.ic_share),
    Group(R.drawable.ic_group),
    Agent(R.drawable.ic_agent),
}
